# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Development server manager for git worktrees"
  homepage "https://github.com/iheanyi/grove"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iheanyi/grove/releases/download/v0.10.0/grove_0.10.0_darwin_amd64.tar.gz"
      sha256 "08e05deacb934bc5b0c04fa7705e6a0249228886f2806faefbb87381e324b6e0"

      def install
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iheanyi/grove/releases/download/v0.10.0/grove_0.10.0_darwin_arm64.tar.gz"
      sha256 "a380ed6385d2dba4f4d494d2d5f2c0b09ee30409b1dd9f6ef9e258f13b6017da"

      def install
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iheanyi/grove/releases/download/v0.10.0/grove_0.10.0_linux_amd64.tar.gz"
      sha256 "fa99c20dc1965b1c8d70f34e1670dbd1baeadb420acf9758599782a20c70e55d"
      def install
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iheanyi/grove/releases/download/v0.10.0/grove_0.10.0_linux_arm64.tar.gz"
      sha256 "f404528e1b237b7e1a3c29c9d78380bee552ca6baa25d2de766642227ee5c2d3"
      def install
        bin.install "grove"
      end
    end
  end

  test do
    system "#{bin}/grove", "version"
  end
end
