# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grove < Formula
  desc "Development server manager for git worktrees"
  homepage "https://github.com/iheanyi/grove"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iheanyi/grove/releases/download/v0.2.6/grove_0.2.6_darwin_amd64.tar.gz"
      sha256 "740267ae344b2af22bb3ca53351a38f615fa580c0bfd07f4c319e74f247ac2c6"

      def install
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iheanyi/grove/releases/download/v0.2.6/grove_0.2.6_darwin_arm64.tar.gz"
      sha256 "9737b4a4c341e95d32ef09fc9e9d651e7d7124ccd291a925b314abb9c8dd1df3"

      def install
        bin.install "grove"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iheanyi/grove/releases/download/v0.2.6/grove_0.2.6_linux_amd64.tar.gz"
      sha256 "ea5294e387a99752a78e24e627deefbe1a5a37e03522833def6b1f7ea9ecad60"
      def install
        bin.install "grove"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iheanyi/grove/releases/download/v0.2.6/grove_0.2.6_linux_arm64.tar.gz"
      sha256 "3ef5ebf66297ae9ad4e240086f10973018911b05147229d11e0fed7a6d36aaab"
      def install
        bin.install "grove"
      end
    end
  end

  test do
    system "#{bin}/grove", "version"
  end
end
